---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: byenedo/alpine-curl
    tag: latest

inputs:
- name: jb-pipeline-example

run:
  path: jb-pipeline-example/ci/scripts/acceptance.sh

params:
  TARGET_URL: