---
resources:
- name: jb-pipeline-example
  type: git
  source:
    uri: https://github.com/jblackman/jb-pipeline-example.git
    branch: master

- name: jb-pipeline-example-go
  type: git
  source:
    uri: https://github.com/jblackman/jb-pipeline-example.git
    branch: master
    paths: [ go-api ]

- name: jb-pipeline-example-web
  type: git
  source:
    uri: https://github.com/jblackman/jb-pipeline-example.git
    branch: master
    paths: [ web-app ]

- name: cf-staging
  type: cf
  source:
    api: ((cf-staging-api))
    username: ((cf-staging-username))
    password: ((cf-staging-password))
    organization: ((cf-staging-organization))
    space: ((cf-staging-space))

- name: cf-prod
  type: cf
  source:
    api: ((cf-prod-api))
    username: ((cf-prod-username))
    password: ((cf-prod-password))
    organization: ((cf-prod-organization))
    space: ((cf-prod-space))

jobs:
- name: unit-go 
  plan:
  - get: jb-pipeline-example
  - get: jb-pipeline-example-go
    trigger: true
  - task: unit-go
    file: jb-pipeline-example/ci/tasks/unit-go.yml

- name: deploy-staging-go
  plan:
  - get: jb-pipeline-example
  - get: jb-pipeline-example-go
    trigger: true
    passed: [ unit-go ]
  - put: cf-staging
    params:
      manifest: jb-pipeline-example/go-api/manifest.yml
      path: jb-pipeline-example/go-api

- name: deploy-staging-web
  plan:
  - get: jb-pipeline-example
  - get: jb-pipeline-example-web
    trigger: true
    passed: [ unit-web ]
  - put: cf-staging
    params:
      manifest: jb-pipeline-example/web-app/manifest.yml
      path: jb-pipeline-example/web-app

- name: acceptance-staging
  plan:
  - get: jb-pipeline-example
  - get: jb-pipeline-example-go
    trigger: true
    passed: [ deploy-staging-go ]
  - get: jb-pipeline-example-web
    trigger: true
    passed: [ deploy-staging-web ]
  - aggregate:
    - task: acceptance-staging-go
      file: jb-pipeline-example/ci/tasks/acceptance.yml
      params:
        TARGET_URL: ((cf-staging-url-go))
    - task: acceptance-staging-web
      file: jb-pipeline-example/ci/tasks/acceptance.yml
      params:
        TARGET_URL: ((cf-staging-url-web))

- name: deploy-prod-go
  plan:
  - get: jb-pipeline-example
  - get: jb-pipeline-example-go
    trigger: true
    passed: [ acceptance-staging ]
  - put: cf-prod
    params:
      manifest: jb-pipeline-example/go-api/manifest.prod.yml
      path: jb-pipeline-example/go-api

- name: unit-web 
  plan:
  - get: jb-pipeline-example
  - get: jb-pipeline-example-web
    trigger: true
  - task: unit-web
    file: jb-pipeline-example/ci/tasks/unit-web.yml



- name: deploy-prod-web
  plan:
  - get: jb-pipeline-example
  - get: jb-pipeline-example-web
    trigger: true
    passed: [ acceptance-staging ]
  - put: cf-prod
    params:
      manifest: jb-pipeline-example/web-app/manifest.prod.yml
      path: jb-pipeline-example/web-app

- name: acceptance-prod
  plan:
  - get: jb-pipeline-example
  - get: jb-pipeline-example-go
    trigger: true
    passed: [ deploy-prod-go ]
  - get: jb-pipeline-example-web
    trigger: true
    passed: [ deploy-prod-web ]
  - aggregate:
    - task: acceptance-prod-web-task
      file: jb-pipeline-example/ci/tasks/acceptance.yml
      params:
        TARGET_URL: ((cf-prod-url-web))
    - task: acceptance-prod-go
      file: jb-pipeline-example/ci/tasks/acceptance.yml
      params:
        TARGET_URL: ((cf-prod-url-go))
